In [1]:
def kwadratowa(m): return all (len (row) == len (m) for row in m)

def LU(macierz):
    try:
        if kwadratowa(macierz) == False:raise
    except:
        raise ValueError("Macierz nie jest kwadratowa")
    
    n = len(macierz)
    U = [[0]*n for x in range(n)]
    L = [[0]*n for x in range(n)]
    for i in range(n):
        for k in range(i, n):
            suma = sum([L[i][j] * U[j][k] for j in range(i)])
            U[i][k] = macierz[i][k] - suma
        for k in range(i, n):
            if i == k:
                L[i][i] = 1
                continue
            suma = sum([L[k][j] * U[j][i] for j in range(i)])
            L[k][i] = (macierz[k][i] - suma) / U[i][i]
    return U, L

In [2]:
import scipy as sp
import scipy.linalg as li
import numpy as np

macierz = np.array([[9, 8, -2, 2, -2], [7, -3, -2, 7, 2], [2, -2, 2, -7, 6], [4, 8, -3, 3, -1], [2, 2, -1, 1, 4]])

In [3]:
U, L = LU(macierz)

print('macierz wejściowa: ')
print(np.array2string(macierz, precision=2), '\n')
print('przekształcone przez funkcję LU: ')
print('macierz górna: ')
print(np.array2string(np.array(U), precision=2), '\n')
print('macierz dolna: ')
print(np.array2string(np.array(L), precision=2), '\n')
print('przekształcone przez funkcję wbudowaną scipy.linalg: ')
print('macierz górna: ')
print(np.array2string(li.lu(macierz)[2], precision=2), '\n')
print('macierz dolna: ')
print(np.array2string(li.lu(macierz)[1], precision=2), '\n')

macierz wejściowa: 
[[ 9  8 -2  2 -2]
 [ 7 -3 -2  7  2]
 [ 2 -2  2 -7  6]
 [ 4  8 -3  3 -1]
 [ 2  2 -1  1  4]] 

przekształcone przez funkcję LU: 
macierz górna: 
[[ 9.    8.   -2.    2.   -2.  ]
 [ 0.   -9.22 -0.44  5.44  3.56]
 [ 0.    0.    2.63 -9.67  4.99]
 [ 0.    0.    0.   -3.83  6.02]
 [ 0.    0.    0.    0.    3.41]] 

macierz dolna: 
[[ 1.    0.    0.    0.    0.  ]
 [ 0.78  1.    0.    0.    0.  ]
 [ 0.22  0.41  1.    0.    0.  ]
 [ 0.44 -0.48 -0.89  1.    0.  ]
 [ 0.22 -0.02 -0.22  0.37  1.  ]] 

przekształcone przez funkcję wbudowaną scipy.linalg: 
macierz górna: 
[[ 9.    8.   -2.    2.   -2.  ]
 [ 0.   -9.22 -0.44  5.44  3.56]
 [ 0.    0.    2.63 -9.67  4.99]
 [ 0.    0.    0.   -3.83  6.02]
 [ 0.    0.    0.    0.    3.41]] 

macierz dolna: 
[[ 1.    0.    0.    0.    0.  ]
 [ 0.78  1.    0.    0.    0.  ]
 [ 0.22  0.41  1.    0.    0.  ]
 [ 0.44 -0.48 -0.89  1.    0.  ]
 [ 0.22 -0.02 -0.22  0.37  1.  ]] 



# Dla miepoprawnej macierzy

In [4]:
macierz2 = np.array([[9, 8, -2, 2, -2], [7, -3, -2, 7, 2], [2, -2, 2, -7, 6], [4, 8, -3, 3, -1], [2, 2, -1, 1, 4, 4]])
macierz2

array([list([9, 8, -2, 2, -2]), list([7, -3, -2, 7, 2]),
       list([2, -2, 2, -7, 6]), list([4, 8, -3, 3, -1]),
       list([2, 2, -1, 1, 4, 4])], dtype=object)

In [5]:
U2, L2 = LU(macierz2)

ValueError: Macierz nie jest kwadratowa